### PR TITLE
fix #3

### LINKED ISSUE #3: Cannot format code including backquote
Shell error occurs when formatting code includeing backquote(`) 

example:
```ocaml
let _ = "`"
```
error

### PR DESCRIPTION
**Pull request by roodni**
I replaced double quote in the string passed to shell with single quote.

### CODE REVIEW

**Comment by badochov** [comment]
i'm not sure what does it change in command and what have you done to replace

**Comment by roodni** [comment]
Single quotes won't interpolate anything, but double quotes will.

Example:
```
$ echo '`echo a`'
`echo a`
$ echo "`echo a`"
a
```

**Comment by roodni** [comment]
By the way, I realized echo command sometimes causes bugs when formatting code including `\`.

Example:
```
let _ = "\\"
```
スクリーンショット 2020-03-22 23 24 23

This seems solved to replace `echo` with `printf '%s'`.

**Comment by badochov** [comment]
thanks for contribution !

**Pull request merged**
